
name: Deploy appEngine

on:
  push:
    branches:
      - main
      - live-coding

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Build & deploy app
        uses: gradle/gradle-build-action@v2
        with:
          arguments: appengineDeploy
